os: linux
dist: xenial
language: node_js
node_js:
 - stable
 - lts/*
jobs:
  include:
    - stage: release
      script:
        - cp ormconfig.circleci-common.json ./ormconfig.json
        - npm run lint
        # - yarn run test
        - npm run package
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_token: "$NPM_API_TOKEN"
        skip_cleanup: true
        on:
          branch: master
